author: tsctsc6
email: tsctsc6@126.com

avatar: "avatar.png"

sidebar: left

show_update_time: true

triangle_badge:
  enable: true
  icon: github
  link: https://github.com/tsctsc6/Hugo-Website

font:
  enable: true
  article:
    - Noto Sans SC
  code:
    - JetBrains Mono

mermaid:
  zoom: true

algolia_search:
  enable: true
  appID: J0995S445Z
  apiKey: 06a6c4bd9cfc552c3d78a034d171fd5f
  indexName: hugo-website
  hits:
    per_page: 10

outdate:
  enable: true

internal_theme:
  light:
  # 高亮代码颜色
    --highlight-selection: "#FFFBCC"
